### ISSUE TITLE
European Journal of Operational Research Template

### ISSUE THREAD

**Issue by ajohnsonGH** [sachsmc/pandoc-journal-templates#5]
I was looking for a Pandoc template for EJOR, it is an Elsevier journal

https://www.elsevier.com/authors/author-schemas/latex-instructions

I am new to Markdown, so perhaps this already exist and I am just looking in the wrong place. Any advice is appreciated.

**Comment by sachsmc** [comment]
Hi there,

I don't support Elsevier journals, but it looks like rticles does: 

https://github.com/rstudio/rticles

See that link for instructions. 

Good luck!
