### ISSUE TITLE
stats-in-med

### ISSUE THREAD

**Issue by Enrique-Barrajon** [sachsmc/pandoc-journal-templates#9]

**Comment by sachsmc** [comment]
What's the issue?

**Comment by Enrique-Barrajon** [comment]
Sorry to bother you.
I just tried to find out how to include bibliography entries other than
articles, such as @Manual, as explained at
https://bookdown.org/yihui/rmarkdown-cookbook/bibliography.html.
But I discovered Stats in Med only allows @Article entry.

Enrique Barrajon MDPhD
enrique.barrajon@gmail.com
